// src/components/common/AuthModal.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { z } from 'zod'

const props = defineProps<{
  mode?: 'login' | 'signup'
  externalError?: string
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'login', payload: { email: string; password: string }): void
  (
    e: 'signup',
    payload: {
      name: string
      email: string
      password: string
      companyName: string
      position: string
      phone: string
    },
  ): void
}>()

const viewMode = ref<'login' | 'signup'>(props.mode ?? 'login')
const externalErrorMessage = ref(props.externalError ?? '')

const loginSchema = z.object({
  email: z.string().min(1, '이메일을 입력하세요.').email('유효한 이메일을 입력하세요.'),
  password: z.string().min(6, '비밀번호는 6자 이상이어야 합니다.'),
  name: z.string().optional(),
  companyName: z.string().optional(),
  position: z.string().optional(),
  phone: z.string().optional(),
  agreeTerms: z.boolean().optional(),
})

const signupSchema = z.object({
  email: z.string().min(1, '이메일을 입력하세요.').email('유효한 이메일을 입력하세요.'),
  password: z.string().min(6, '비밀번호는 6자 이상이어야 합니다.'),
  name: z.string().min(1, '이름을 입력하세요.'),
  companyName: z.string().min(1, '회사명을 입력하세요.'),
  position: z.string().min(1, '직책을 입력하세요.'),
  phone: z
    .string()
    .min(1, '연락처를 입력하세요.')
    .regex(/^[\d-+\s()]+$/, '유효한 연락처 형식을 입력하세요.'),
  agreeTerms: z.boolean().refine((v) => v === true, { message: '이용 약관에 동의해야 합니다.' }),
})

const validationSchema = computed(() =>
  toTypedSchema(viewMode.value === 'login' ? loginSchema : signupSchema),
)

const { handleSubmit, defineField, errors, resetForm } = useForm({
  validationSchema,
  initialValues: {
    email: '',
    password: '',
    name: '',
    companyName: '',
    position: '담당자',
    phone: '',
    agreeTerms: false,
  },
})

const [email] = defineField('email')
const [password] = defineField('password')
const [name] = defineField('name')
const [companyName] = defineField('companyName')
const [position] = defineField('position')
const [phone] = defineField('phone')
const [agreeTerms] = defineField('agreeTerms')

watch(
  () => props.mode,
  (value) => {
    if (value && value !== viewMode.value) {
      viewMode.value = value
      externalErrorMessage.value = ''
      resetForm()
    }
  },
)

watch(
  () => props.externalError,
  (value) => {
    externalErrorMessage.value = value ?? ''
  },
)

const title = computed(() => (viewMode.value === 'login' ? '로그인' : '회원가입'))
const ctaText = computed(() => (viewMode.value === 'login' ? '로그인' : '계정 생성'))
const switchText = computed(() =>
  viewMode.value === 'login' ? '계정이 없으신가요? 회원가입' : '이미 계정이 있으신가요? 로그인',
)

const firstError = computed(() => {
  if (externalErrorMessage.value) return externalErrorMessage.value
  return (
    errors.value.email ||
    errors.value.password ||
    errors.value.name ||
    errors.value.companyName ||
    errors.value.position ||
    errors.value.phone ||
    errors.value.agreeTerms ||
    ''
  )
})

const onSubmit = handleSubmit((values) => {
  externalErrorMessage.value = ''
  if (viewMode.value === 'signup') {
    emit('signup', {
      name: values.name ?? '',
      email: values.email,
      password: values.password,
      companyName: values.companyName ?? '',
      position: values.position || '담당자',
      phone: values.phone || '010-0000-0000',
    })
    return
  }
  emit('login', { email: values.email, password: values.password })
})

function toggleMode() {
  viewMode.value = viewMode.value === 'login' ? 'signup' : 'login'
  externalErrorMessage.value = ''
  resetForm()
}

function closeModal() {
  emit('close')
}
</script>

<template>
  <div class="auth-modal-overlay" @click="closeModal">
    <div class="auth-modal" @click.stop>
      <div class="auth-modal-header">
        <div>
          <p class="eyebrow">ROOTMATCHING</p>
          <h2>{{ title }}</h2>
        </div>
        <button class="close-button" type="button" aria-label="닫기" @click="closeModal">x</button>
      </div>

      <p class="auth-modal-description">
        {{
          viewMode === 'login'
            ? '이메일과 비밀번호로 로그인하세요.'
            : '회원가입 후 RootMatching을 시작하세요.'
        }}
      </p>

      <form class="auth-form" @submit.prevent="onSubmit">
        <div class="form-group">
          <label for="email">이메일</label>
          <input
            id="email"
            v-model="email"
            type="email"
            class="input"
            placeholder="example@company.com"
            autocomplete="email"
          />
        </div>

        <div v-if="viewMode === 'signup'" class="form-group">
          <label for="name">이름</label>
          <input
            id="name"
            v-model="name"
            type="text"
            class="input"
            placeholder="홍길동"
            autocomplete="name"
          />
        </div>

        <div v-if="viewMode === 'signup'" class="form-group">
          <label for="companyName">회사명</label>
          <input
            id="companyName"
            v-model="companyName"
            type="text"
            class="input"
            placeholder="회사명을 입력하세요"
            autocomplete="organization"
          />
        </div>

        <div class="form-group">
          <label for="password">비밀번호</label>
          <input
            id="password"
            v-model="password"
            type="password"
            class="input"
            placeholder="6자 이상 입력"
            :autocomplete="viewMode === 'login' ? 'current-password' : 'new-password'"
          />
        </div>

        <div v-if="viewMode === 'signup'" class="form-grid">
          <div class="form-group">
            <label for="position">직책</label>
            <input
              id="position"
              v-model="position"
              type="text"
              class="input"
              placeholder="대표 / 담당자"
            />
          </div>
          <div class="form-group">
            <label for="phone">연락처</label>
            <input
              id="phone"
              v-model="phone"
              type="tel"
              class="input"
              placeholder="010-1234-5678"
              autocomplete="tel"
            />
          </div>
        </div>

        <div v-if="viewMode === 'signup'" class="form-group checkbox-group">
          <input id="agreeTerms" v-model="agreeTerms" type="checkbox" />
          <label for="agreeTerms">이용 약관 및 개인정보 처리방침에 동의합니다.</label>
        </div>

        <p v-if="firstError" class="error-message">{{ firstError }}</p>

        <button class="btn btn-primary btn-lg w-full" type="submit">{{ ctaText }}</button>
        <button class="btn btn-ghost btn-sm w-full" type="button" @click="toggleMode">
          {{ switchText }}
        </button>
      </form>
    </div>
  </div>
</template>

<style scoped>
.auth-modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(15, 23, 42, 0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  z-index: 2000;
}

.auth-modal {
  width: min(100%, 520px);
  background: white;
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-lg);
  padding: 28px;
  border: 1px solid var(--border);
}

.auth-modal-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 18px;
}

.eyebrow {
  margin-bottom: 8px;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--primary);
}

.auth-modal-header h2 {
  margin: 0;
  font-size: 24px;
  color: var(--text-primary);
}

.close-button {
  background: transparent;
  border: none;
  font-size: 24px;
  line-height: 1;
  color: var(--text-secondary);
  cursor: pointer;
}

.auth-modal-description {
  margin-bottom: 20px;
  color: var(--text-secondary);
  line-height: 1.6;
}

.auth-form {
  display: grid;
  gap: 16px;
}

.form-group {
  display: grid;
  gap: 8px;
}

.form-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

.checkbox-group {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 10px;
  align-items: center;
}

.checkbox-group input {
  width: 18px;
  height: 18px;
}

.error-message {
  color: var(--error);
  font-size: 13px;
  margin-bottom: 0;
}

button.w-full {
  width: 100%;
}
</style>

// apps/web/src/components/auth/AuthModal.tsx
'use client'

import { useEffect, useState, type ReactNode } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { cn } from '@/lib/cn'
import { mockCompanies } from '@/data/companies'
import { mockCurrentUser } from '@/data/users'
import { useUserDispatch } from '@/state/UserContext'
import { AppButton } from '@/components/ui/AppButton'

type AuthTab = 'login' | 'register'

const loginSchema = z.object({
  email: z.string().email('올바른 이메일 형식이 아닙니다'),
  password: z.string().min(6, '비밀번호는 6자 이상이어야 합니다'),
})

const registerSchema = z.object({
  email: z.string().email('올바른 이메일 형식이 아닙니다'),
  password: z.string().min(6, '비밀번호는 6자 이상이어야 합니다'),
  name: z.string().min(1, '이름을 입력해주세요'),
  companyName: z.string().min(1, '회사명을 입력해주세요'),
  position: z.string().optional(),
  phone: z.string().optional(),
  terms: z.boolean().refine((value) => value, '약관 동의가 필요합니다'),
})

type LoginFormValues = z.infer<typeof loginSchema>
type RegisterFormValues = z.input<typeof registerSchema>

interface AuthModalProps {
  open: boolean
  onClose: () => void
  defaultTab?: AuthTab
  className?: string
}

const tabStyles: Record<AuthTab, string> = {
  login: '로그인',
  register: '회원가입',
}

const inputClassName =
  'mt-2 h-12 w-full rounded-xl border border-slate-300 px-4 outline-none transition focus:border-brand focus:ring-4 focus:ring-brand-light'

export function AuthModal({ open, onClose, defaultTab = 'login', className }: AuthModalProps) {
  const [activeTab, setActiveTab] = useState<AuthTab>(defaultTab)
  const [submitError, setSubmitError] = useState('')
  const dispatch = useUserDispatch()
  const loginForm = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: { email: '', password: '' },
  })
  const registerForm = useForm<RegisterFormValues>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      email: '',
      password: '',
      name: '',
      companyName: '',
      position: '',
      phone: '',
      terms: false,
    },
  })

  useEffect(() => {
    if (open) {
      setActiveTab(defaultTab)
      setSubmitError('')
    }
  }, [defaultTab, open])

  if (!open) return null

  function submitLogin(values: LoginFormValues) {
    setSubmitError('')
    if (values.email !== 'hong@techsolution.co.kr' || values.password !== '123456') {
      setSubmitError('이메일 또는 비밀번호가 올바르지 않습니다')
      return
    }
    dispatch({ type: 'user/login', payload: mockCurrentUser })
    onClose()
  }

  function submitRegister(values: RegisterFormValues) {
    setSubmitError('')
    const company = mockCompanies.find(() => true)
    if (!company) {
      setSubmitError('가입에 필요한 회사 정보를 찾을 수 없습니다')
      return
    }
    dispatch({
      type: 'user/register',
      payload: {
        ...values,
        id: 'new-user',
        company,
        role: 'admin',
      },
    })
    onClose()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/50 px-4 py-8">
      <dialog
        open
        className={cn(
          'm-0 w-full max-w-lg rounded-2xl border border-border bg-white p-0 shadow-lg',
          className,
        )}
      >
        <div className="flex items-center justify-between border-b border-border px-6 py-5">
          <h2 className="text-2xl font-bold text-ink-950">계정 시작하기</h2>
          <button
            type="button"
            onClick={onClose}
            className="flex h-10 w-10 items-center justify-center rounded-xl text-ink-400 transition hover:bg-surface-muted hover:text-ink-950"
            aria-label="닫기"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-6">
          <div className="mb-6 grid grid-cols-2 rounded-xl border border-border bg-surface-muted p-1">
            {(['login', 'register'] as const).map((tab) => (
              <button
                key={tab}
                type="button"
                onClick={() => {
                  setActiveTab(tab)
                  setSubmitError('')
                }}
                className={cn(
                  'rounded-lg px-4 py-2.5 text-sm font-bold transition',
                  activeTab === tab
                    ? 'bg-white text-brand shadow-sm'
                    : 'text-ink-700 hover:text-brand',
                )}
              >
                {tabStyles[tab]}
              </button>
            ))}
          </div>

          {submitError && (
            <p className="mb-4 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-bold text-danger">
              {submitError}
            </p>
          )}

          {activeTab === 'login' ? (
            <form onSubmit={loginForm.handleSubmit(submitLogin)} className="space-y-4">
              <Field label="이메일" error={loginForm.formState.errors.email?.message}>
                <input
                  type="email"
                  autoComplete="email"
                  className={inputClassName}
                  {...loginForm.register('email')}
                />
              </Field>
              <Field label="비밀번호" error={loginForm.formState.errors.password?.message}>
                <input
                  type="password"
                  autoComplete="current-password"
                  className={inputClassName}
                  {...loginForm.register('password')}
                />
              </Field>
              <AppButton type="submit" size="lg" fullWidth>
                로그인
              </AppButton>
            </form>
          ) : (
            <form onSubmit={registerForm.handleSubmit(submitRegister)} className="space-y-4">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <Field label="이름" error={registerForm.formState.errors.name?.message}>
                  <input
                    type="text"
                    className={inputClassName}
                    {...registerForm.register('name')}
                  />
                </Field>
                <Field label="회사명" error={registerForm.formState.errors.companyName?.message}>
                  <input
                    type="text"
                    className={inputClassName}
                    {...registerForm.register('companyName')}
                  />
                </Field>
              </div>
              <Field label="이메일" error={registerForm.formState.errors.email?.message}>
                <input
                  type="email"
                  autoComplete="email"
                  className={inputClassName}
                  {...registerForm.register('email')}
                />
              </Field>
              <Field label="비밀번호" error={registerForm.formState.errors.password?.message}>
                <input
                  type="password"
                  autoComplete="new-password"
                  className={inputClassName}
                  {...registerForm.register('password')}
                />
              </Field>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <Field label="직책" error={registerForm.formState.errors.position?.message}>
                  <input
                    type="text"
                    className={inputClassName}
                    {...registerForm.register('position')}
                  />
                </Field>
                <Field label="연락처" error={registerForm.formState.errors.phone?.message}>
                  <input
                    type="tel"
                    className={inputClassName}
                    {...registerForm.register('phone')}
                  />
                </Field>
              </div>
              <label className="flex items-start gap-3 rounded-xl border border-border bg-surface-muted p-4 text-sm font-semibold text-ink-700">
                <input
                  type="checkbox"
                  className="mt-1 h-4 w-4 accent-brand"
                  {...registerForm.register('terms')}
                />
                <span>서비스 이용약관과 개인정보 처리방침에 동의합니다.</span>
              </label>
              {registerForm.formState.errors.terms?.message && (
                <p className="text-sm font-semibold text-danger">
                  {registerForm.formState.errors.terms.message}
                </p>
              )}
              <AppButton type="submit" size="lg" fullWidth>
                회원가입
              </AppButton>
            </form>
          )}
        </div>
      </dialog>
    </div>
  )
}

function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) {
  return (
    <label className="block text-sm font-bold text-ink-700">
      {label}
      {children}
      {error && <span className="mt-1 block text-sm font-semibold text-danger">{error}</span>}
    </label>
  )
}
