// apps/web/src/components/ui/ProcessStepper.tsx
'use client'

import { CheckCircle } from 'lucide-react'
import { cn } from '@/lib/cn'

interface ProcessStep {
  title: string
  description: string
}

interface ProcessStepperProps {
  steps: ProcessStep[]
  currentStep: number
  className?: string
}

export function ProcessStepper({ steps, currentStep, className }: ProcessStepperProps) {
  return (
    <ol className={cn('grid grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-3', className)}>
      {steps.map((step, index) => {
        const stepNumber = index + 1
        const isCurrent = stepNumber === currentStep
        const isDone = stepNumber < currentStep

        return (
          <li key={step.title} className="rounded-xl border border-border bg-surface-muted p-4">
            <div
              className={cn(
                'mb-3 flex h-9 w-9 items-center justify-center rounded-full text-sm font-black',
                isCurrent
                  ? 'bg-brand text-white'
                  : isDone
                    ? 'bg-emerald-500 text-white'
                    : 'bg-white text-ink-400',
              )}
            >
              {isDone ? <CheckCircle className="h-5 w-5" /> : stepNumber}
            </div>
            <p className="text-sm font-bold text-ink-950">{step.title}</p>
            <p className="mt-1 text-xs leading-5 text-ink-400">{step.description}</p>
          </li>
        )
      })}
    </ol>
  )
}

// src/components/common/ProcessStepper.vue
<script setup lang="ts">
interface ProcessStep {
  title: string
  description?: string
}

defineProps<{
  steps: ProcessStep[]
  currentStep?: number
}>()
</script>

<template>
  <ol class="grid grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-4">
    <li
      v-for="(step, index) in steps"
      :key="step.title"
      class="relative rounded-xl border bg-white p-5 shadow-sm"
      :class="index + 1 <= (currentStep ?? 1) ? 'border-blue-200' : 'border-slate-200'"
    >
      <div class="flex items-start gap-4">
        <div
          class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-base font-bold"
          :class="
            index + 1 <= (currentStep ?? 1)
              ? 'bg-blue-600 text-white'
              : 'bg-slate-100 text-slate-500'
          "
        >
          {{ index + 1 }}
        </div>
        <div>
          <h3 class="text-base font-bold text-slate-950">{{ step.title }}</h3>
          <p v-if="step.description" class="mt-1 text-sm leading-6 text-slate-600">
            {{ step.description }}
          </p>
        </div>
      </div>
    </li>
  </ol>
</template>
